version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: before_script.sh
      timeout: 50
      runas: root

  AfterInstall:
    - location: after_script.sh
      timeout: 50
      runas: root
